### ISSUE TITLE
Change game font to something more readable

### ISSUE THREAD

**Issue by jcowgill** [sepr-hou/atc-game#23]

**Comment by jk1993** [comment]
Should be able to do this by adding gdx-freetype to the maven dependencies (it's included in libgdx in the extensions folder). This basically lets you use '.ttf' (true type) fonts so you can natively generate them at the right size instead of stretching bitmap fonts. I've had a play around but am struggling to get it working

**Comment by jcowgill** [comment]
That sounds like a good idea, but is it nessesary - could we not just use a higher resolution bitmap font?

I haven't looked into it too much but gdx-freetype has some native libraries so you need a maven dependency for those to. Something like:

```
<dependency>
  <groupId>com.badlogicgames.gdx</groupId>
  <artifactId>gdx-freetype</artifactId>
  <version>${gdx.version}</version>
</dependency>

<dependency>
  <groupId>com.badlogicgames.gdx</groupId>
  <artifactId>gdx-freetype-platform</artifactId>
  <version>${gdx.version}</version>
  <classifier>natives-desktop</classifier>
</dependency>
```
